FROM node:16-alpine
WORKDIR /app

RUN apk update && apk add git

ENV NODE_ENV=production
ENV PORT=8080
ARG API
ENV NEXT_PUBLIC_API=${API}
ARG URI
ENV NEXT_PUBLIC_URI=${URI}
ARG ENVIRONMENT
ENV NEXT_PUBLIC_ENVIRONMENT=${ENVIRONMENT}
ARG GA_TRACKING_ID
ENV NEXT_PUBLIC_GA_TRACKING_ID=${GA_TRACKING_ID}
ARG HOTJAR_SITE_ID
ENV NEXT_PUBLIC_HOTJAR_SITE_ID=${HOTJAR_SITE_ID}
ARG COOKIE_SECRET_CURRENT
ENV COOKIE_SECRET_CURRENT=${COOKIE_SECRET_CURRENT}
ARG COOKIE_SECRET_PREVIOUS
ENV COOKIE_SECRET_PREVIOUS=${COOKIE_SECRET_PREVIOUS}
ARG FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
ARG FIREBASE_CLIENT_EMAIL
ENV FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
ARG FIREBASE_PRIVATE_KEY
ENV FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
ARG FIREBASE_PUBLIC_API_KEY
ENV NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY=${FIREBASE_PUBLIC_API_KEY}
ARG FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
ARG FIREBASE_DATABASE_URL
ENV NEXT_PUBLIC_FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
ARG COOKIE_SECURE
ENV NEXT_PUBLIC_COOKIE_SECURE=${COOKIE_SECURE}

COPY package.json yarn.lock ./
RUN yarn install --production=false --frozen-lockfile

COPY . ./

RUN yarn build

CMD node server.js