import type {GetStaticPropsResult, NextPage} from 'next';
import Head from 'next/head';
import {graphqlClient} from '../graphql/GraphqlClient';
import {COUNTRY_ISO} from '../graphql/query/CountryIsoQuery';

interface Props {
  countryIso: {emoji: string; name: string; rank: number}[];
}

export const getServerSideProps = async (): Promise<GetStaticPropsResult<Props>> => {
  const countryIsoResult = await graphqlClient.query<{countryIso: {emoji: string; name: string; rank: number}[]}>({
    query: COUNTRY_ISO
  });

  return {
    props: {
      countryIso: countryIsoResult.data.countryIso
    }
  };
};

const Home: NextPage<Props> = ({countryIso}) => {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Next.js!</h1>
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th
                scope="col"
                className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Emoji
              </th>
              <th
                scope="col"
                className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Title
              </th>
              <th
                scope="col"
                className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Rank
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {countryIso.map((row, index) => {
              return (
                <tr key={index}>
                  <td className="px-6 py-4 whitespace-nowrap">{row.emoji}</td>
                  <td className="px-6 py-4 whitespace-nowrap">{row.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap">{row.rank}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </main>
    </>
  );
};

export default Home;
